name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build app (optional, remove if not needed)
        run: npm run build

      - name: Start app server
        run: npm run serve &

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:8081
          timeout: 60

      - name: Run Cypress tests
        run: npx cypress run
