name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Start frontend dev server
        working-directory: frontend
        run: npm run serve &

      - name: Wait for frontend to be ready
        uses: francium/wait-on-action@v1
        with:
          url: http://localhost:8081
          timeout: 60

      - name: Run Cypress tests
        working-directory: frontend
        run: npx cypress run
