name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Start frontend dev server
        working-directory: frontend
        run: npm run serve &

      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:8082
          timeout: 60

      - name: Run Cypress tests
        working-directory: frontend
        # Run Cypress and keep video/screenshot artifacts on failure
        run: npx cypress run --spec "frontend/cypress/e2e/**/*.js"

      - name: Upload Cypress videos (only if tests fail)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: frontend/cypress/videos

      - name: Upload Cypress screenshots (only if tests fail)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
