name: Cypress Tests Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: List Cypress spec files for debugging
        working-directory: frontend
        run: ls -l cypress/e2e/

      - name: Start frontend dev server
        working-directory: frontend
        run: npm run serve &

      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          entryPoint: http://localhost:8080
          args: 30

      - name: Run Cypress Create and Submit Record Test
        working-directory: frontend
        run: npx cypress run --spec "cypress/e2e/incident_create_spec.js"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
